Element-wise Operation:

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 3, 2])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 5 5]
[-3 -1  1]
[4 6 6]
[0.25       0.66666667 1.5       ]


Aggregate Functions:

In [ ]:
array = np.array([1, 2, 3, 4, 5])
print(np.sum(array))
print(np.mean(array))
print(np.min(array))
print(np.max(array))
print(np.std(array))
print(np.var(array))


15
3.0
1
5
1.4142135623730951
2.0


Matrix Multiplication:
(1.)This line calculates the standard deviation of the elements in the array using the np.std() function and prints the result. Standard deviation is a measure of the spread or dispersion of data around the mean.
(2.)This line calculates the variance of the elements in the array using the np.var() function and prints the result. Variance is another measure of the spread of data, and it is the square of the standard deviation.

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.dot(a, b))
print("\n")
print(np.matmul(a, b))
print("\n")
print(np.dot(b, a))
print("\n")
print(np.matmul(b, a))

[[19 22]
 [43 50]]


[[19 22]
 [43 50]]


[[23 34]
 [31 46]]


[[23 34]
 [31 46]]


**Broadcasting:**

Scalar Operation:

In [ ]:
a = np.array([1, 2, 3])
b = 2
print(a + b)
print("\n")
print(a - b)
print("\n")
print(a * b)
print("\n")
print(a / b)

[3 4 5]


[-1  0  1]


[2 4 6]


[0.5 1.  1.5]


Array Operation:

In [ ]:
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])
print(a + b)
print("\n")
print(a - b)
print("\n")
print(a * b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


[[ -9 -19 -29]
 [ -8 -18 -28]
 [ -7 -17 -27]]


[[10 20 30]
 [20 40 60]
 [30 60 90]]


**Broadcasting Rules**

In [ ]:
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])
print(a + b)
print("\n")
print(a - b)
print("\n")
print(a * b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


[[ -9 -19 -29]
 [ -8 -18 -28]
 [ -7 -17 -27]]


[[10 20 30]
 [20 40 60]
 [30 60 90]]


**Aplication in Data Science and Machine Learning**

Data Preprocessing:

In [ ]:
data = np.array([1, 2, 3, 4, 5])
normalized_data = (data - np.min(data)) / (np.max(data) - np.min(data))
print(normalized_data)

[0.   0.25 0.5  0.75 1.  ]


Random Sampling:

In [ ]:
random_data = np.random.rand(5)
print(random_data)

[0.93852062 0.51154936 0.10534733 0.44350635 0.8733074 ]


Vectorized Operation:

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9, 1])
result1 = a*b
result2 = a * b + c
print(result1)
print("\n")
print(result2)

[ 4 10 18 28]


[11 18 27 29]


**Advanced Topic and Optimization in NumPy**

Memory Management and Views:

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = a[2:4]
b[0] = 100
print(a)

[  1   2 100   4   5]


In-place Operation:

In [ ]:
a = np.array([1, 2, 3, 4, 5])
a*= 2
print(a)

[ 2  4  6  8 10]


Optimized Linear Algebra:

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.dot(a, b))
print("\n")



[[19 22]
 [43 50]]


[[19 22]
 [43 50]]


**Exercises**

Ex-01:

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)

[5 7 9]


Ex-02:

In [ ]:
random_data = np.random.rand(3,3)
print(random_data)

[[0.87887852 0.15408502 0.80608393]
 [0.46069005 0.93033098 0.32171248]
 [0.06793141 0.91909938 0.11460317]]


Ex-03:

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.dot(a , b))

[[19 22]
 [43 50]]


Ex-04:

In [ ]:
a = np.array([2, 3])
a += 10

print(a)

[12 13]


Ex-05:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
cumulative_sum = np.cumsum(arr)
print(cumulative_sum)

[ 1  3  6 10 15]


Ex-06:

In [ ]:
a = np.array([1, 2, 3])
b = np.array([[4, 5, 6], [7, 8, 9]])

print(a+b)

[[ 5  7  9]
 [ 8 10 12]]


Ex-07:

In [ ]:


matrix = np.random.randint(1, 101, size=(4, 4))
print("Matrix:\n", matrix)

max_value = np.max(matrix)
min_value = np.min(matrix)
print("\nMaximum value:", max_value)
print("Minimum value:", min_value)

Matrix:
 [[52 26 64 65]
 [29 89 63 77]
 [ 9 45  3 95]
 [32 84 84 38]]

Maximum value: 95
Minimum value: 3


Ex-08:

In [ ]:
identity_matrix = np.eye(5)

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Ex-09: